"""empty message

Revision ID: 0081b9683b1d
Revises: fc74d2274aa4
Create Date: 2021-08-21 10:47:47.420551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0081b9683b1d'
down_revision = 'fc74d2274aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('people_ibfk_1', 'people', type_='foreignkey')
    op.drop_column('people', 'user_id')
    op.drop_constraint('planet_ibfk_1', 'planet', type_='foreignkey')
    op.drop_column('planet', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('planet_ibfk_1', 'planet', 'user', ['user_id'], ['id'])
    op.add_column('people', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('people_ibfk_1', 'people', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
