"""empty message

Revision ID: 428e4dda4cee
Revises: 3e7d07c0ff07
Create Date: 2021-08-21 08:04:18.251155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '428e4dda4cee'
down_revision = '3e7d07c0ff07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('birth_year', sa.String(length=40), nullable=False),
    sa.Column('gender', sa.String(length=200), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('mass', sa.Integer(), nullable=False),
    sa.Column('hair_color', sa.String(length=200), nullable=False),
    sa.Column('skin_color', sa.String(length=200), nullable=False),
    sa.Column('eye_color', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('characters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('birth_year', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('height', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mass', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hair_color', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('skin_color', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('eye_color', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='characters_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('people')
    # ### end Alembic commands ###
